# Generated by Django 3.2 on 2025-01-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_alter_artista_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_obra', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
