# Generated by Django 3.2 on 2025-01-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0004_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='id_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas_obra', to=settings.AUTH_USER_MODEL),
        ),
    ]
