# Generated by Django 3.2 on 2025-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0005_alter_obra_id_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artista',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
